#! /bin/sh

# sxhkd is installed in custom dir and bashrc hasn't been sourced yet
# can't source bashrc directly as bash native calls will error out in zsh
export PATH="/home/akd/dotapps/local/bin:$PATH"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Custom configs

nitrogen --restore
#pkill polybar
#~/.config/polybar/launch.sh --forest
compton &
xscreensaver &
