#! /bin/bash

# sxhkd is installed in a custom dir and bashrc hasn't been sourced yet
# can't source bashrc directly as it will exec out zsh
export USER="akd"
export HOME="/home/$USER"
export PATH="$HOME/dotapps/local/bin:$PATH"

. "$HOME/.myDisplays.sh"

echo "$display1" > /tmp/out.txt
# Run primary display always
bspc monitor "$display1" -d 1 2 3 4 5
echo $? >> /tmp/out.txt

# Run a single external Monitor if exists
if [[ ! -z "$externalMonitor" ]]; then
    bspc monitor "$display2" -d 6 7 8 9 10
fi

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         3
bspc config window_gap          12
bspc config border_radius        2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
# Firefox download dialogues to appear floating 
# Check with xprop the wm class/name info
bspc rule -a 'Firefox:*:Library' state=floating follow=on center=on

# Custom configs

# Nord theme
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#4c566a"
bspc config focused_border_color "#d8dee9"
bspc config presel_feedback_color "#6272a4"

# Follow mouse for focus
bspc config focus_follows_pointer true

nitrogen --restore
pkill polybar
~/.config/polybar/launch.sh --shapes
compton &
xscreensaver &
xss-lock -- xscreensaver-command --lock &
pkill dunst; dunst &
xsetroot -cursor_name left_ptr

# Remove unplugged and disabled monitors
bspc config remove_unplugged_monitors true
#bspc config remove_disabled_monitors true


# Disable caps lock button, replace it with both press of left and right shift keys
setxkbmap -option "caps:none"
setxkbmap -option "shift:both_capslock"


bspc rule -a 
