#! /bin/bash

# sxhkd is installed in a custom dir and bashrc hasn't been sourced yet
# can't source bashrc directly as it will exec out zsh
export USER="akd"
export HOME="/home/$USER"
export PATH="$HOME/dotapps/local/bin:$PATH"

. "$HOME/.myDisplays.sh"

echo "$display1" > /tmp/out.txt
# Run primary display always
bspc monitor "$display1" -d 1 2 3 4 5
echo $? >> /tmp/out.txt

# Run a single external Monitor if exists
if [[ ! -z "$externalMonitor" ]]; then
    bspc monitor "$display2" -d 6 7 8 9 10
fi

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Custom configs

nitrogen --restore
pkill polybar
~/.config/polybar/launch.sh --forest
compton &
xscreensaver &
